# Generated by Django 4.0 on 2022-03-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remmeber_me',
            field=models.BooleanField(blank=True),
        ),
    ]
